using Microsoft.AspNetCore.Mvc;
using Woola.PhotoManager.Backend.Domain.Repositories;
using Woola.PhotoManager.Shared.Models;

namespace Woola.PhotoManager.Backend.WebApi.Controllers;

[ApiController]
[Route("api/v1/[controller]")]
public class TagsController : ControllerBase
{
    private readonly ITagRepository _tagRepo;

    public TagsController(ITagRepository tagRepo) => _tagRepo = tagRepo;

    [HttpGet]
    public async Task<ActionResult<List<TagDto>>> GetAll()
    {
        var tags = await _tagRepo.GetAllAsync();
        return Ok(tags.Select(t => new TagDto
        {
            Id = t.Id,
            Name = t.Name,
            Category = t.Category,
            IsAutoGenerated = t.IsAutoGenerated,
            UsageCount = t.UsageCount,
            CreatedAt = t.CreatedAt
        }).ToList());
    }

    [HttpGet("{name}/photos")]
    public async Task<ActionResult<PagedApiResponse<PhotoDto>>> GetPhotos(
        string name,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 50)
    {
        var result = await _tagRepo.GetPhotosAsync(new[] { name }, page, pageSize);
        return Ok(PagedApiResponse<PhotoDto>.Ok(
            result.Items.Select(p => new PhotoDto
            {
                Id = p.Id,
                FileName = p.FileName,
                Path = p.Path,
                Hash = p.Hash,
                FileSize = p.FileSize,
                DateTaken = p.DateTaken,
                Width = p.Width,
                Height = p.Height,
                Status = p.Status,
                ThumbnailUrl = p.ThumbnailPath != null ? $"/thumbnails/{p.ThumbnailPath}" : null,
                CreatedAt = p.CreatedAt
            }).ToList(),
            result.TotalCount, page, pageSize));
    }
}
