using Woola.PhotoManager.Backend.Domain.Entities;

namespace Woola.PhotoManager.Backend.Domain.Repositories;

public interface IRepository<T> where T : BaseEntity
{
    Task<T?> GetByIdAsync(int id, CancellationToken ct = default);
    Task<int> InsertAsync(T entity, CancellationToken ct = default);
    Task UpdateAsync(T entity, CancellationToken ct = default);
    Task DeleteAsync(int id, CancellationToken ct = default);
    Task<int> GetTotalCountAsync(CancellationToken ct = default);
}

public interface IPhotoRepository : IRepository<Photo>
{
    Task<PagedResult<Photo>> GetPhotosAsync(int page, int pageSize, string? sortBy, string? sortDir, CancellationToken ct = default);
    Task<PagedResult<Photo>> SearchAsync(string query, int page, int pageSize, CancellationToken ct = default);
    Task<Photo?> GetByHashAsync(string hash, CancellationToken ct = default);
    Task<Photo?> GetByPathAsync(string path, CancellationToken ct = default);
    Task<int> InsertBatchAsync(IEnumerable<Photo> photos, CancellationToken ct = default);
    Task UpdateStatusAsync(int id, string status, CancellationToken ct = default);
    Task UpdateThumbnailAsync(int id, string thumbnailPath, CancellationToken ct = default);
    Task<List<Photo>> GetByDateRangeAsync(DateTime start, DateTime end, CancellationToken ct = default);
    Task<List<Photo>> GetWithGpsAsync(CancellationToken ct = default);
}

public interface IAlbumRepository : IRepository<Album>
{
    Task<List<Album>> GetAllAsync(CancellationToken ct = default);
    Task<PagedResult<Photo>> GetPhotosAsync(int albumId, int page, int pageSize, CancellationToken ct = default);
    Task AddPhotoAsync(int albumId, int photoId, CancellationToken ct = default);
    Task RemovePhotoAsync(int albumId, int photoId, CancellationToken ct = default);
    Task<bool> HasPhotoAsync(int albumId, int photoId, CancellationToken ct = default);
    Task<List<int>> GetPhotoIdsAsync(int albumId, CancellationToken ct = default);
}

public interface ITagRepository : IRepository<Tag>
{
    Task<List<Tag>> GetAllAsync(CancellationToken ct = default);
    Task<Tag?> GetByNameAsync(string name, CancellationToken ct = default);
    Task<Tag> GetOrCreateAsync(string name, string category, bool autoGenerated, CancellationToken ct = default);
    Task AddToPhotoAsync(int photoId, int tagId, double confidence, string source, CancellationToken ct = default);
    Task RemoveFromPhotoAsync(int photoId, int tagId, CancellationToken ct = default);
    Task<List<Tag>> GetForPhotoAsync(int photoId, CancellationToken ct = default);
    Task<PagedResult<Photo>> GetPhotosAsync(IEnumerable<string> tagNames, int page, int pageSize, CancellationToken ct = default);
    Task<List<(Tag Tag, int Count)>> GetTopTagsAsync(int limit, CancellationToken ct = default);
}

public interface IFaceRepository : IRepository<Face>
{
    Task<List<Face>> GetAllAsync(CancellationToken ct = default);
    Task<List<Face>> GetForPhotoAsync(int photoId, CancellationToken ct = default);
    Task<List<Face>> GetWithEncodingsAsync(CancellationToken ct = default);
    Task UpdatePersonAsync(int faceId, string? personName, string? personId, CancellationToken ct = default);
    Task<List<(string? PersonName, int Count)>> GetPersonSummaryAsync(CancellationToken ct = default);
    Task<PagedResult<Photo>> GetPhotosByPersonAsync(string personName, int page, int pageSize, CancellationToken ct = default);
    Task DeleteForPhotoAsync(int photoId, CancellationToken ct = default);
}
