using MediatR;
using Woola.PhotoManager.Backend.Domain.Repositories;
using Woola.PhotoManager.Shared.Models;

namespace Woola.PhotoManager.Backend.Application.Photos.Queries;

public record GetPhotoDetailQuery(int Id) : IRequest<PhotoDetailDto?>;

public class GetPhotoDetailHandler : IRequestHandler<GetPhotoDetailQuery, PhotoDetailDto?>
{
    private readonly IPhotoRepository _photoRepo;
    private readonly ITagRepository _tagRepo;
    private readonly IFaceRepository _faceRepo;

    public GetPhotoDetailHandler(
        IPhotoRepository photoRepo,
        ITagRepository tagRepo,
        IFaceRepository faceRepo)
    {
        _photoRepo = photoRepo;
        _tagRepo = tagRepo;
        _faceRepo = faceRepo;
    }

    public async Task<PhotoDetailDto?> Handle(GetPhotoDetailQuery query, CancellationToken ct)
    {
        var photo = await _photoRepo.GetByIdAsync(query.Id, ct);
        if (photo == null) return null;

        var tags = await _tagRepo.GetForPhotoAsync(query.Id, ct);
        var faces = await _faceRepo.GetForPhotoAsync(query.Id, ct);

        return new PhotoDetailDto
        {
            Id = photo.Id,
            FileName = photo.FileName,
            Path = photo.Path,
            Hash = photo.Hash,
            FileSize = photo.FileSize,
            DateTaken = photo.DateTaken,
            Width = photo.Width,
            Height = photo.Height,
            Status = photo.Status,
            ThumbnailUrl = photo.ThumbnailPath != null
                ? $"/thumbnails/{photo.ThumbnailPath}"
                : null,
            CameraModel = photo.CameraModel,
            LensModel = photo.LensModel,
            Aperture = photo.Aperture,
            ShutterSpeed = photo.ShutterSpeed,
            Iso = photo.Iso,
            FocalLength = photo.FocalLength,
            Latitude = photo.Latitude,
            Longitude = photo.Longitude,
            CreatedAt = photo.CreatedAt,
            Tags = tags.Select(t => new TagDto
            {
                Id = t.Id,
                Name = t.Name,
                Category = t.Category,
                IsAutoGenerated = t.IsAutoGenerated,
                UsageCount = t.UsageCount,
                CreatedAt = t.CreatedAt
            }).ToList(),
            Faces = faces.Select(f => new FaceDto
            {
                Id = f.Id,
                PhotoId = f.PhotoId,
                PersonName = f.PersonName,
                PersonId = f.PersonId,
                X = f.X, Y = f.Y,
                Width = f.Width, Height = f.Height,
                Confidence = f.Confidence,
                IsUserConfirmed = f.IsUserConfirmed,
                CreatedAt = f.CreatedAt
            }).ToList()
        };
    }
}
