namespace Woola.PhotoManager.Domain.Entities;

public class Tag
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = "Custom";
    public bool IsAutoGenerated { get; set; }
    public int UsageCount { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Poblado solo cuando se consulta junto con PhotoTags (no existe en tabla Tags)
    public float Confidence { get; set; } = 1.0f;
}
