using Dapper;
using Woola.PhotoManager.Common.Helpers;
using Woola.PhotoManager.Domain.Entities;
using Woola.PhotoManager.Infrastructure.Database;

namespace Woola.PhotoManager.Infrastructure.Repositories;

public class TagRepository : IRepository<Tag, int>
{
    private readonly SqliteConnectionFactory _connectionFactory;

    public TagRepository(SqliteConnectionFactory connectionFactory)
    {
        _connectionFactory = connectionFactory;
    }

    public async Task<int> GetOrCreateTagAsync(string name, string category = "Custom", bool isAutoGenerated = false)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            INSERT OR IGNORE INTO Tags (Name, Category, IsAutoGenerated, UsageCount, CreatedAt)
            VALUES (@Name, @Category, @IsAutoGenerated, 0, @CreatedAt);
            
            SELECT Id FROM Tags WHERE Name = @Name;
        ";

        return await connection.ExecuteScalarAsync<int>(sql, new
        {
            Name = name.ToLowerInvariant(),
            Category = category,
            IsAutoGenerated = isAutoGenerated,
            CreatedAt = DateTime.UtcNow.ToIsoString()
        });
    }

    public async Task AddTagToPhotoAsync(int photoId, int tagId, double confidence, string source)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            INSERT OR IGNORE INTO PhotoTags (PhotoId, TagId, Confidence, Source, CreatedAt)
            VALUES (@PhotoId, @TagId, @Confidence, @Source, @CreatedAt);
            
            UPDATE Tags SET UsageCount = UsageCount + 1 WHERE Id = @TagId;
        ";

        await connection.ExecuteAsync(sql, new
        {
            PhotoId = photoId,
            TagId = tagId,
            Confidence = confidence,
            Source = source,
            CreatedAt = DateTime.UtcNow.ToIsoString()
        });
    }

    public async Task<IEnumerable<Tag>> GetTagsForPhotoAsync(int photoId)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            SELECT t.Id, t.Name, t.Category, t.IsAutoGenerated, t.UsageCount,
                   pt.Confidence
            FROM PhotoTags pt
            JOIN Tags t ON t.Id = pt.TagId
            WHERE pt.PhotoId = @PhotoId
            ORDER BY pt.Confidence DESC, t.Name
        ";

        return await connection.QueryAsync<Tag>(sql, new { PhotoId = photoId });
    }

    public async Task<IEnumerable<Tag>> GetAllTagsAsync()
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            SELECT Id, Name, Category, IsAutoGenerated, UsageCount, CreatedAt
            FROM Tags
            ORDER BY UsageCount DESC
        ";

        return await connection.QueryAsync<Tag>(sql);
    }

    public async Task<Dictionary<int, List<Tag>>> GetTagsBatchAsync(IEnumerable<int> photoIds)
    {
        using var connection = _connectionFactory.CreateConnection();
        const string sql = @"
            SELECT pt.PhotoId, t.Id, t.Name, t.Category, t.IsAutoGenerated, t.UsageCount, pt.Confidence
            FROM PhotoTags pt
            JOIN Tags t ON t.Id = pt.TagId
            WHERE pt.PhotoId IN @PhotoIds
            ORDER BY pt.Confidence DESC";

        var rows = await connection.QueryAsync<(int PhotoId, int Id, string Name, string Category,
            bool IsAutoGenerated, int UsageCount, double Confidence)>(
            sql, new { PhotoIds = photoIds.ToList() });

        return rows.GroupBy(r => r.PhotoId)
                   .ToDictionary(
                       g => g.Key,
                       g => g.Select(r => new Tag
                       {
                           Id = r.Id, Name = r.Name, Category = r.Category,
                           IsAutoGenerated = r.IsAutoGenerated, UsageCount = r.UsageCount,
                           Confidence = (float)r.Confidence
                       }).ToList());
    }

    public async Task<IEnumerable<Photo>> GetPhotosByTagsAsync(IEnumerable<string> tagNames, int limit = 1000)
    {
        var names = tagNames.Select(n => n.ToLowerInvariant()).ToList();
        if (names.Count == 0) return [];
        using var connection = _connectionFactory.CreateConnection();
        const string sql = @"
            SELECT Id, Path, Hash, FileSize, DateTaken, Width, Height,
                   Latitude, Longitude, CameraModel, LensModel, Aperture, ShutterSpeed,
                   Iso, FocalLength, Orientation, Status, ThumbnailPath, CreatedAt, LastIndexedAt
            FROM Photos
            WHERE (
                SELECT COUNT(DISTINCT t.Name)
                FROM PhotoTags pt JOIN Tags t ON t.Id = pt.TagId
                WHERE pt.PhotoId = Photos.Id AND t.Name IN @Names
            ) = @TagCount
            ORDER BY COALESCE(DateTaken, CreatedAt) DESC
            LIMIT @Limit";
        return await connection.QueryAsync<Photo>(sql,
            new { Names = names, TagCount = names.Count, Limit = limit });
    }

    /// <summary>IMP-T3-004: Versión paginada con total para el filtro de tags en MainViewModel.</summary>
    public async Task<(List<Photo> Photos, int Total)> GetPhotosByTagsPagedAsync(
        IEnumerable<string> tagNames, int limit, int offset)
    {
        var names = tagNames.Select(n => n.ToLowerInvariant()).ToList();
        if (names.Count == 0) return ([], 0);

        using var connection = _connectionFactory.CreateConnection();

        const string countSql = @"
            SELECT COUNT(*) FROM Photos
            WHERE (
                SELECT COUNT(DISTINCT t.Name)
                FROM PhotoTags pt JOIN Tags t ON t.Id = pt.TagId
                WHERE pt.PhotoId = Photos.Id AND t.Name IN @Names
            ) = @TagCount";

        var total = await connection.ExecuteScalarAsync<int>(
            countSql, new { Names = names, TagCount = names.Count });

        const string sql = @"
            SELECT Id, Path, Hash, FileSize, DateTaken, Width, Height,
                   Latitude, Longitude, CameraModel, LensModel, Aperture, ShutterSpeed,
                   Iso, FocalLength, Orientation, Status, ThumbnailPath, CreatedAt, LastIndexedAt
            FROM Photos
            WHERE (
                SELECT COUNT(DISTINCT t.Name)
                FROM PhotoTags pt JOIN Tags t ON t.Id = pt.TagId
                WHERE pt.PhotoId = Photos.Id AND t.Name IN @Names
            ) = @TagCount
            ORDER BY COALESCE(DateTaken, CreatedAt) DESC
            LIMIT @Limit OFFSET @Offset";

        var photos = (await connection.QueryAsync<Photo>(sql,
            new { Names = names, TagCount = names.Count, Limit = limit, Offset = offset })).ToList();

        return (photos, total);
    }

    public async Task<IEnumerable<Photo>> GetPhotosByTagAsync(string tagName, int limit = 100)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
        SELECT p.Id, p.Path, p.Hash, p.FileSize, p.DateTaken, p.Width, p.Height,
               p.Latitude, p.Longitude, p.CameraModel, p.LensModel, p.Aperture, p.ShutterSpeed, p.Iso, p.FocalLength, p.Orientation,
               p.Status, p.ThumbnailPath, p.CreatedAt, p.LastIndexedAt
        FROM PhotoTags pt
        JOIN Photos p ON p.Id = pt.PhotoId
        JOIN Tags t ON t.Id = pt.TagId
        WHERE t.Name = @TagName
        ORDER BY COALESCE(p.DateTaken, p.CreatedAt) DESC
        LIMIT @Limit
    ";

        var photos = await connection.QueryAsync<Photo>(sql, new { TagName = tagName.ToLowerInvariant(), Limit = limit });

        // Convertir fechas
        foreach (var photo in photos)
        {
            if (photo.DateTaken.HasValue)
            {
                // Ya debería estar bien
            }
        }

        return photos;
    }

    // ── IRepository<Tag, int> ─────────────────────────────────────────────────

    async Task<Tag?> IRepository<Tag, int>.GetByIdAsync(int id, CancellationToken ct)
    {
        using var connection = _connectionFactory.CreateConnection();
        return await connection.QueryFirstOrDefaultAsync<Tag>(
            "SELECT Id, Name, Category, IsAutoGenerated, UsageCount, CreatedAt FROM Tags WHERE Id = @Id",
            new { Id = id });
    }

    async Task<int> IRepository<Tag, int>.InsertAsync(Tag entity, CancellationToken ct)
        => await GetOrCreateTagAsync(entity.Name, entity.Category, entity.IsAutoGenerated);

    async Task IRepository<Tag, int>.UpdateAsync(Tag entity, CancellationToken ct)
    {
        using var connection = _connectionFactory.CreateConnection();
        await connection.ExecuteAsync(
            "UPDATE Tags SET Name = @Name, Category = @Category WHERE Id = @Id",
            new { entity.Name, entity.Category, entity.Id });
    }

    async Task<bool> IRepository<Tag, int>.ExistsAsync(int id, CancellationToken ct)
    {
        using var connection = _connectionFactory.CreateConnection();
        return await connection.ExecuteScalarAsync<bool>(
            "SELECT EXISTS(SELECT 1 FROM Tags WHERE Id = @Id)", new { Id = id });
    }
}