using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Dapper;
using Woola.PhotoManager.Infrastructure.Database;

namespace Woola.PhotoManager.Infrastructure.Repositories;

public class TagRepository
{
    private readonly SqliteConnectionFactory _connectionFactory;

    public TagRepository(SqliteConnectionFactory connectionFactory)
    {
        _connectionFactory = connectionFactory;
    }

    public async Task<int> GetOrCreateTagAsync(string name, string category = "Custom", bool isAutoGenerated = false)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            INSERT OR IGNORE INTO Tags (Name, Category, IsAutoGenerated, UsageCount, CreatedAt)
            VALUES (@Name, @Category, @IsAutoGenerated, 0, @CreatedAt);
            
            SELECT Id FROM Tags WHERE Name = @Name;
        ";

        return await connection.ExecuteScalarAsync<int>(sql, new
        {
            Name = name.ToLowerInvariant(),
            Category = category,
            IsAutoGenerated = isAutoGenerated,
            CreatedAt = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds()
        });
    }

    public async Task AddTagToPhotoAsync(int photoId, int tagId, double confidence, string source)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            INSERT OR IGNORE INTO PhotoTags (PhotoId, TagId, Confidence, Source, CreatedAt)
            VALUES (@PhotoId, @TagId, @Confidence, @Source, @CreatedAt);
            
            UPDATE Tags SET UsageCount = UsageCount + 1 WHERE Id = @TagId;
        ";

        await connection.ExecuteAsync(sql, new
        {
            PhotoId = photoId,
            TagId = tagId,
            Confidence = confidence,
            Source = source,
            CreatedAt = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds()
        });
    }
}
