namespace Woola.PhotoManager.Backend.Domain.Entities;

public class Tag : BaseEntity
{
    public string Name { get; private set; } = string.Empty;
    public string Category { get; private set; } = "Custom";
    public bool IsAutoGenerated { get; private set; }
    public int UsageCount { get; private set; }

    public ICollection<PhotoTag> PhotoTags { get; private set; } = new List<PhotoTag>();

    public static Tag Create(string name, string category, bool isAutoGenerated = false)
    {
        return new Tag
        {
            Name = name,
            Category = category,
            IsAutoGenerated = isAutoGenerated,
            UsageCount = 0,
            CreatedAt = DateTime.UtcNow
        };
    }

    public void IncrementUsage() => UsageCount++;
    public void DecrementUsage()
    {
        if (UsageCount > 0) UsageCount--;
    }
}
