namespace Woola.PhotoManager.Shared.Models;

public class TagDto
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Category { get; set; } = "Custom";
    public bool IsAutoGenerated { get; set; }
    public int UsageCount { get; set; }
    public double? Confidence { get; set; }
    public DateTime CreatedAt { get; set; }
}
