using Dapper;
using Woola.PhotoManager.Domain.Entities;
using Woola.PhotoManager.Infrastructure.Database;
using Woola.PhotoManager.Infrastructure.Repositories;

namespace Woola.PhotoManager.Core.Services;

public class AutoTaggingService : IAutoTaggingService
{
    private readonly TagRepository _tagRepository;
    private readonly SqliteConnectionFactory _connectionFactory;

    public AutoTaggingService(TagRepository tagRepository, SqliteConnectionFactory connectionFactory)
    {
        _tagRepository = tagRepository;
        _connectionFactory = connectionFactory;
    }

    public async Task<List<string>> GenerateTagsForPhotoAsync(Photo photo)
    {
        var tags = new List<string>();

        // Tag por año
        var year = photo.DateTaken?.Year ?? photo.CreatedAt.Year;
        tags.Add($"año_{year}");

        // Tag por mes
        var month = photo.DateTaken?.Month ?? photo.CreatedAt.Month;
        var monthNames = new[] { "enero", "febrero", "marzo", "abril", "mayo", "junio",
                                  "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre" };
        tags.Add($"mes_{monthNames[month - 1]}");

        // Tag por estación
        string season = GetSeason(photo.DateTaken ?? photo.CreatedAt);
        tags.Add($"estación_{season}");

        // Tag por década
        int decade = (year / 10) * 10;
        tags.Add($"década_{decade}s");

        // Tag por cámara (si existe)
        if (!string.IsNullOrEmpty(photo.CameraModel))
        {
            var cameraBrand = GetCameraBrand(photo.CameraModel);
            tags.Add($"cámara_{cameraBrand}");
        }

        // Tag por ubicación (si existe GPS)
        if (photo.Latitude.HasValue && photo.Longitude.HasValue)
        {
            tags.Add("con_gps");
        }
        else
        {
            tags.Add("sin_gps");
        }

        return tags.Distinct().ToList();
    }

    public async Task ApplyTagsToPhotoAsync(int photoId, List<string> tags)
    {
        foreach (var tagName in tags)
        {
            var tagId = await _tagRepository.GetOrCreateTagAsync(tagName, "AutoGenerated", true);
            await _tagRepository.AddTagToPhotoAsync(photoId, tagId, 1.0, "AutoTaggingService");
        }
    }

    public async Task UpdateTagsForExistingPhotoAsync(int photoId, Photo photo)
    {
        await RemoveAutoTagsForPhotoAsync(photoId);
        var tags = await GenerateTagsForPhotoAsync(photo);
        await ApplyTagsToPhotoAsync(photoId, tags);
    }

    private async Task RemoveAutoTagsForPhotoAsync(int photoId)
    {
        using var connection = _connectionFactory.CreateConnection();

        const string sql = @"
            DELETE FROM PhotoTags 
            WHERE PhotoId = @PhotoId 
            AND TagId IN (SELECT Id FROM Tags WHERE IsAutoGenerated = 1)
        ";

        await connection.ExecuteAsync(sql, new { PhotoId = photoId });
    }

    private string GetSeason(DateTime date)
    {
        int month = date.Month;
        int day = date.Day;

        if (month == 12 || month == 1 || month == 2)
            return "invierno";
        if (month == 3 || month == 4 || month == 5)
            return "primavera";
        if (month == 6 || month == 7 || month == 8)
            return "verano";
        return "otoño";
    }

    private string GetCameraBrand(string cameraModel)
    {
        var modelLower = cameraModel.ToLower();
        if (modelLower.Contains("canon")) return "canon";
        if (modelLower.Contains("nikon")) return "nikon";
        if (modelLower.Contains("sony")) return "sony";
        if (modelLower.Contains("fujifilm")) return "fujifilm";
        if (modelLower.Contains("olympus")) return "olympus";
        if (modelLower.Contains("panasonic")) return "panasonic";
        if (modelLower.Contains("leica")) return "leica";
        if (modelLower.Contains("iphone")) return "iphone";
        if (modelLower.Contains("samsung")) return "samsung";
        if (modelLower.Contains("huawei")) return "huawei";
        if (modelLower.Contains("xiaomi")) return "xiaomi";
        return "otra";
    }
}