using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Data.Sqlite;

namespace Woola.PhotoManager.Infrastructure.Database;

public class SqliteConnectionFactory
{
    private readonly string _connectionString;

    public SqliteConnectionFactory(string databasePath)
    {
        var directory = Path.GetDirectoryName(databasePath);
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);

        _connectionString = $"Data Source={databasePath}";
        InitializeDatabase();
    }

    private void InitializeDatabase()
    {
        using var connection = new SqliteConnection(_connectionString);
        connection.Open();

        var sql = @"
        CREATE TABLE IF NOT EXISTS Photos (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            Path TEXT NOT NULL UNIQUE,
            Hash TEXT NOT NULL UNIQUE,
            FileSize INTEGER NOT NULL,
            DateTaken TEXT,  -- ← Cambiado a TEXT para guardar ISO string
            Width INTEGER,
            Height INTEGER,
            Status TEXT NOT NULL,
            ThumbnailPath TEXT,
            CreatedAt TEXT NOT NULL,  -- ← Cambiado a TEXT
            LastIndexedAt TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_photos_hash ON Photos(Hash);
        CREATE INDEX IF NOT EXISTS idx_photos_status ON Photos(Status);

        CREATE VIRTUAL TABLE IF NOT EXISTS Photos_FTS USING fts5(
            Path,
            Tags,
            content=Photos,
            content_rowid=Id
        );

        CREATE TABLE IF NOT EXISTS Tags (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            Name TEXT NOT NULL UNIQUE,
            Category TEXT NOT NULL,
            IsAutoGenerated INTEGER NOT NULL,
            UsageCount INTEGER NOT NULL DEFAULT 0,
            CreatedAt TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS PhotoTags (
            PhotoId INTEGER NOT NULL,
            TagId INTEGER NOT NULL,
            Confidence REAL NOT NULL,
            Source TEXT NOT NULL,
            CreatedAt TEXT NOT NULL,
            PRIMARY KEY (PhotoId, TagId),
            FOREIGN KEY(PhotoId) REFERENCES Photos(Id) ON DELETE CASCADE,
            FOREIGN KEY(TagId) REFERENCES Tags(Id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS Faces (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            PhotoId INTEGER NOT NULL,
            PersonName TEXT,
            X INTEGER NOT NULL,
            Y INTEGER NOT NULL,
            Width INTEGER NOT NULL,
            Height INTEGER NOT NULL,
            Encoding BLOB,
            Confidence REAL NOT NULL,
            IsUserConfirmed INTEGER NOT NULL,
            CreatedAt TEXT NOT NULL,
            FOREIGN KEY(PhotoId) REFERENCES Photos(Id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_faces_person ON Faces(PersonName);
    ";

        using var command = new SqliteCommand(sql, connection);
        command.ExecuteNonQuery();
    }

    public SqliteConnection CreateConnection()
    {
        var connection = new SqliteConnection(_connectionString);
        connection.Open();
        return connection;
    }
}
