using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Data.Sqlite;

namespace Woola.PhotoManager.Infrastructure.Database;

public class SqliteConnectionFactory
{
    private readonly string _connectionString;

    public SqliteConnectionFactory(string databasePath)
    {
        var directory = Path.GetDirectoryName(databasePath);
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);

        _connectionString = $"Data Source={databasePath}";
        InitializeDatabase();
    }


    private void InitializeDatabase()
    {
        using var connection = new SqliteConnection(_connectionString);
        connection.Open();

        // WAL mode + memory tuning (IMP-T3-006)
        using var walCmd = new SqliteCommand(@"
            PRAGMA journal_mode  = WAL;
            PRAGMA synchronous   = NORMAL;
            PRAGMA cache_size    = -32000;
            PRAGMA temp_store    = MEMORY;
            PRAGMA mmap_size     = 268435456;
            PRAGMA foreign_keys  = ON;
        ", connection);
        walCmd.ExecuteNonQuery();

        var sql = @"
        CREATE TABLE IF NOT EXISTS Photos (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            Path TEXT NOT NULL UNIQUE,
            Hash TEXT NOT NULL UNIQUE,
            FileSize INTEGER NOT NULL,
            DateTaken TEXT,
            Width INTEGER,
            Height INTEGER,
            Latitude REAL,
            Longitude REAL,
            CameraModel TEXT,
            LensModel TEXT,
            Aperture REAL,
            ShutterSpeed REAL,
            Iso INTEGER,
            FocalLength INTEGER,
            Orientation INTEGER,
            Status TEXT NOT NULL,
            ThumbnailPath TEXT,
            CreatedAt TEXT NOT NULL,
            LastIndexedAt TEXT
        );

        -- Índices nuevos para búsqueda por ubicación
        CREATE INDEX IF NOT EXISTS idx_photos_lat_lon ON Photos(Latitude, Longitude);
        CREATE INDEX IF NOT EXISTS idx_photos_camera ON Photos(CameraModel);
        CREATE INDEX IF NOT EXISTS idx_photos_iso ON Photos(Iso);
        CREATE INDEX IF NOT EXISTS idx_photos_aperture ON Photos(Aperture);

        -- Resto de tablas igual...
        CREATE INDEX IF NOT EXISTS idx_photos_hash ON Photos(Hash);
        CREATE INDEX IF NOT EXISTS idx_photos_status ON Photos(Status);
        CREATE INDEX IF NOT EXISTS idx_photos_datetaken ON Photos(DateTaken);

        -- FTS5
        CREATE VIRTUAL TABLE IF NOT EXISTS Photos_FTS USING fts5(
            Path,
            Tags,
            content=Photos,
            content_rowid=Id
        );

        -- Tags
        CREATE TABLE IF NOT EXISTS Tags (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            Name TEXT NOT NULL UNIQUE,
            Category TEXT NOT NULL,
            IsAutoGenerated INTEGER NOT NULL,
            UsageCount INTEGER NOT NULL DEFAULT 0,
            CreatedAt TEXT NOT NULL
        );

        -- PhotoTags
        CREATE TABLE IF NOT EXISTS PhotoTags (
            PhotoId INTEGER NOT NULL,
            TagId INTEGER NOT NULL,
            Confidence REAL NOT NULL,
            Source TEXT NOT NULL,
            CreatedAt TEXT NOT NULL,
            PRIMARY KEY (PhotoId, TagId),
            FOREIGN KEY(PhotoId) REFERENCES Photos(Id) ON DELETE CASCADE,
            FOREIGN KEY(TagId) REFERENCES Tags(Id) ON DELETE CASCADE
        );

        -- Faces
        CREATE TABLE IF NOT EXISTS Faces (
        Id INTEGER PRIMARY KEY AUTOINCREMENT,
        PhotoId INTEGER NOT NULL,
        PersonName TEXT,
        PersonId TEXT,                    -- ← NUEVA COLUMNA
        X INTEGER NOT NULL,
        Y INTEGER NOT NULL,
        Width INTEGER NOT NULL,
        Height INTEGER NOT NULL,
        Encoding BLOB,
        Confidence REAL NOT NULL,
        IsUserConfirmed INTEGER NOT NULL,
        CreatedAt TEXT NOT NULL,
        FOREIGN KEY(PhotoId) REFERENCES Photos(Id) ON DELETE CASCADE
    );

        CREATE INDEX IF NOT EXISTS idx_faces_person ON Faces(PersonName);

        -- G1: Álbumes
        CREATE TABLE IF NOT EXISTS Albums (
            Id INTEGER PRIMARY KEY AUTOINCREMENT,
            Name TEXT NOT NULL,
            Description TEXT,
            CoverPhotoId INTEGER,
            CreatedAt TEXT NOT NULL,
            FOREIGN KEY(CoverPhotoId) REFERENCES Photos(Id) ON DELETE SET NULL
        );

        CREATE TABLE IF NOT EXISTS AlbumPhotos (
            AlbumId INTEGER NOT NULL,
            PhotoId INTEGER NOT NULL,
            AddedAt TEXT NOT NULL,
            PRIMARY KEY (AlbumId, PhotoId),
            FOREIGN KEY(AlbumId) REFERENCES Albums(Id) ON DELETE CASCADE,
            FOREIGN KEY(PhotoId) REFERENCES Photos(Id) ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS idx_albumphotos_album ON AlbumPhotos(AlbumId);

        -- IMP-T3-006B: índice para ORDER BY COALESCE(DateTaken, CreatedAt) DESC
        CREATE INDEX IF NOT EXISTS idx_photos_sort
            ON Photos(COALESCE(DateTaken, CreatedAt) DESC);
    ";

        using var command = new SqliteCommand(sql, connection);
        command.ExecuteNonQuery();
    }

    public SqliteConnection CreateConnection()
    {
        var connection = new SqliteConnection(_connectionString);
        connection.Open();
        return connection;
    }
}
