using Microsoft.EntityFrameworkCore;
using Woola.PhotoManager.Backend.Domain.Entities;
using Woola.PhotoManager.Backend.Domain.Repositories;
using Woola.PhotoManager.Backend.Infrastructure.Data;

namespace Woola.PhotoManager.Backend.Infrastructure.Repositories;

public class TagRepository : ITagRepository
{
    private readonly WoolaDbContext _db;

    public TagRepository(WoolaDbContext db) => _db = db;

    public async Task<Tag?> GetByIdAsync(int id, CancellationToken ct = default)
        => await _db.Tags.AsNoTracking().FirstOrDefaultAsync(t => t.Id == id, ct);

    public async Task<Tag?> GetByNameAsync(string name, CancellationToken ct = default)
        => await _db.Tags.AsNoTracking().FirstOrDefaultAsync(t => t.Name == name, ct);

    public async Task<List<Tag>> GetAllAsync(CancellationToken ct = default)
        => await _db.Tags
            .OrderByDescending(t => t.UsageCount)
            .AsNoTracking()
            .ToListAsync(ct);

    public async Task<Tag> GetOrCreateAsync(string name, string category, bool autoGenerated, CancellationToken ct = default)
    {
        var existing = await _db.Tags.FirstOrDefaultAsync(t => t.Name == name, ct);
        if (existing != null) return existing;

        var tag = Tag.Create(name, category, autoGenerated);
        _db.Tags.Add(tag);
        await _db.SaveChangesAsync(ct);
        return tag;
    }

    public async Task AddToPhotoAsync(int photoId, int tagId, double confidence, string source, CancellationToken ct = default)
    {
        var exists = await _db.PhotoTags.AnyAsync(pt => pt.PhotoId == photoId && pt.TagId == tagId, ct);
        if (!exists)
        {
            _db.PhotoTags.Add(PhotoTag.Create(photoId, tagId, confidence, source));
            await _db.Tags.Where(t => t.Id == tagId)
                .ExecuteUpdateAsync(s => s.SetProperty(t => t.UsageCount, t => t.UsageCount + 1), ct);
            await _db.SaveChangesAsync(ct);
        }
    }

    public async Task RemoveFromPhotoAsync(int photoId, int tagId, CancellationToken ct = default)
    {
        var pt = await _db.PhotoTags.FirstOrDefaultAsync(x => x.PhotoId == photoId && x.TagId == tagId, ct);
        if (pt != null)
        {
            _db.PhotoTags.Remove(pt);
            await _db.Tags.Where(t => t.Id == tagId)
                .ExecuteUpdateAsync(s => s.SetProperty(t => t.UsageCount, t => t.UsageCount > 0 ? t.UsageCount - 1 : 0), ct);
            await _db.SaveChangesAsync(ct);
        }
    }

    public async Task<List<Tag>> GetForPhotoAsync(int photoId, CancellationToken ct = default)
        => await _db.PhotoTags
            .Where(pt => pt.PhotoId == photoId)
            .Include(pt => pt.Tag)
            .Select(pt => pt.Tag!)
            .AsNoTracking()
            .ToListAsync(ct);

    public async Task<PagedResult<Photo>> GetPhotosAsync(
        IEnumerable<string> tagNames, int page, int pageSize, CancellationToken ct = default)
    {
        var names = tagNames.ToList();
        var query = _db.PhotoTags
            .Where(pt => names.Contains(pt.Tag!.Name))
            .GroupBy(pt => pt.PhotoId)
            .Where(g => g.Count() == names.Count)
            .Select(g => g.Key);

        var total = await query.CountAsync(ct);
        var photoIds = await query
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync(ct);

        var photos = await _db.Photos.AsNoTracking()
            .Where(p => photoIds.Contains(p.Id))
            .OrderByDescending(p => p.DateTaken ?? p.CreatedAt)
            .ToListAsync(ct);

        return new PagedResult<Photo>(photos, total, page, pageSize);
    }

    public async Task<List<(Tag Tag, int Count)>> GetTopTagsAsync(int limit, CancellationToken ct = default)
    {
        var tags = await _db.Tags
            .OrderByDescending(t => t.UsageCount)
            .Take(limit)
            .AsNoTracking()
            .ToListAsync(ct);

        return tags.Select(t => (t, t.UsageCount)).ToList();
    }

    public async Task<int> InsertAsync(Tag entity, CancellationToken ct = default)
    {
        _db.Tags.Add(entity);
        await _db.SaveChangesAsync(ct);
        return entity.Id;
    }

    public async Task UpdateAsync(Tag entity, CancellationToken ct = default)
    {
        _db.Tags.Update(entity);
        await _db.SaveChangesAsync(ct);
    }

    public async Task DeleteAsync(int id, CancellationToken ct = default)
    {
        var tag = await _db.Tags.FindAsync(new object[] { id }, ct);
        if (tag != null)
        {
            tag.SoftDelete();
            await _db.SaveChangesAsync(ct);
        }
    }

    public async Task<int> GetTotalCountAsync(CancellationToken ct = default)
        => await _db.Tags.CountAsync(ct);
}
